name: Auto-build

on: [push, pull_request, workflow_dispatch]

jobs:        
  windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
        matrix:
            build_type: ["Release", "Debug"]
            arch: ["x64"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Compile with MSVC for Windows
      run: |
        cmake -A ${{ matrix.arch }} . -B build_msvc
        cmake --build build_msvc --config ${{ matrix.build_type }}

    - name: Run tests
      run: |
        ctest --test-dir build_msvc -C ${{ matrix.build_type }}

      shell: bash
    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Windows_${{ matrix.build_type }}_${{ matrix.arch }}
        path: |
          ${{ github.workspace }}\bin\HadesSavesExtractor.exe
          ${{ github.workspace }}\scripts\extract.bat
          ${{ github.workspace }}\scripts\import.bat
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    strategy:
        matrix:
            build_type: ["Release", "Debug"]
            arch: ["x64"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Compile for Linux
      run: |
        cmake . -B build ${{ matrix.arch == 'x86' && '-DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32' || '' }} -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build build --config ${{ matrix.build_type }}
      shell: bash
    - name: Run tests
      run:
        ctest --test-dir build -C ${{ matrix.build_type }}
    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux_${{ matrix.build_type }}_${{ matrix.arch }}
        path: |
          ${{ github.workspace }}\bin\HadesSavesExtractor
